name: fancy_bottom_navigation_plus
description: An animated Bottom Navigation Bar for Flutter apps, icon animates into place, colors are customisable..
version: 1.0.2
homepage: https://github.com/jinosh05/fancy_bottom_navigation_plus

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
